# -*- coding: utf-8 -*-
"""Build both programs + the Setup, and prepare the update files for GitHub.

  python build.py            -> build\\dist\\FAWAZ Tenders\\  (two .exe sharing one _internal folder)
                                updates\\FAWAZ-Tenders-Setup.exe + updates\\latest.json
Bump version.txt before a new release, build, then commit + push the updates folder:
the installed programs pick the new version up by themselves.
Needs: pip install pyinstaller pymupdf openpyxl pywin32 pillow
"""
import json, shutil, subprocess, sys, zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
APP, BUILD, UPD = ROOT / "app", ROOT / "build", ROOT / "updates"
VERSION = (ROOT / "version.txt").read_text(encoding="utf-8").strip()
CONF = json.loads((ROOT / "build_config.json").read_text(encoding="utf-8"))
SEED = Path(CONF.get("awards_seed", ""))
# the programs only need the standard library + pymupdf + openpyxl; keep the heavy optional stuff out
EXCLUDES = ["numpy", "pandas", "scipy", "numba", "llvmlite", "PIL", "lxml", "matplotlib", "tkinter", "IPython",
            "jedi", "pytest", "sklearn", "win32com", "pythoncom", "pywintypes", "win32api", "pythonwin", "notebook",
            "sympy", "cryptography", "babel", "docutils", "setuptools", "pkg_resources"]


def update_url():
    if not CONF.get("github_owner"):
        return ""
    return (f"https://raw.githubusercontent.com/{CONF['github_owner']}/{CONF['repo']}/"
            f"{CONF.get('branch', 'main')}/updates/latest.json")


def make_icons():
    from PIL import Image, ImageDraw, ImageFont
    out = {}
    for key, (bg, letter) in {"capt": ("#1F4E78", "ت"), "gulf": ("#0f5c4d", "د"), "setup": ("#16806b", "F")}.items():
        img = Image.new("RGBA", (256, 256), (0, 0, 0, 0))
        d = ImageDraw.Draw(img)
        d.rounded_rectangle((8, 8, 248, 248), radius=52, fill=bg)
        font = ImageFont.truetype(r"C:\Windows\Fonts\arialbd.ttf", 150)
        d.text((128, 132), letter, font=font, fill="white", anchor="mm")
        p = BUILD / f"{key}.ico"
        img.save(p, sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
        out[key] = p
    return out


def spec_text(icons, info):
    ui, seed = str(APP / "ui"), str(SEED) if SEED.exists() else ""
    datas = [(ui, "ui"), (str(info), ".")]
    if seed:
        datas.append((seed, "seed"))
    return f'''# generated by build.py
X = {EXCLUDES!r}
a1 = Analysis([r"{APP / 'gulf_app.py'}"], pathex=[r"{APP}"], datas={datas!r}, hiddenimports=["capt_tool", "gulf_directory"], excludes=X)
a2 = Analysis([r"{APP / 'capt_app.py'}"], pathex=[r"{APP}"], datas={datas!r}, hiddenimports=["capt_tool"], excludes=X)
p1, p2 = PYZ(a1.pure), PYZ(a2.pure)
e1 = EXE(p1, a1.scripts, [], exclude_binaries=True, name="FAWAZ Gulf Directory", console=False, icon=r"{icons['gulf']}")
e2 = EXE(p2, a2.scripts, [], exclude_binaries=True, name="FAWAZ CAPT Awards", console=False, icon=r"{icons['capt']}")
COLLECT(e1, a1.binaries, a1.datas, e2, a2.binaries, a2.datas, name="FAWAZ Tenders")
'''


def run(cmd):
    print(">", " ".join(map(str, cmd)))
    subprocess.run(cmd, check=True)


def main():
    BUILD.mkdir(exist_ok=True)
    UPD.mkdir(exist_ok=True)
    info = BUILD / "_build_info.json"
    info.write_text(json.dumps({"version": VERSION, "update_url": update_url()}, ensure_ascii=False), encoding="utf-8")
    icons = make_icons()
    spec = BUILD / "fawaz_tenders.spec"
    spec.write_text(spec_text(icons, info), encoding="utf-8")
    run([sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", "--distpath", str(BUILD / "dist"),
         "--workpath", str(BUILD / "work"), str(spec)])
    dist = BUILD / "dist" / "FAWAZ Tenders"
    payload = BUILD / "payload.zip"
    with zipfile.ZipFile(payload, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:
        for f in dist.rglob("*"):
            if f.is_file():
                z.write(f, f.relative_to(dist))
    run([sys.executable, "-m", "PyInstaller", "--noconfirm", "--onefile", "--windowed", "--name", "FAWAZ-Tenders-Setup",
         "--icon", str(icons["setup"]), "--distpath", str(BUILD / "setup"), "--workpath", str(BUILD / "work-setup"),
         "--specpath", str(BUILD), "--add-data", f"{payload};.", "--add-data", f"{info};.",
         "--hidden-import", "win32com.shell", "--hidden-import", "pythoncom",
         *sum((["--exclude-module", m] for m in EXCLUDES if m not in ("tkinter", "win32com", "pythoncom", "pywintypes", "win32api")), []),
         str(ROOT / "installer" / "setup_main.py")])
    setup = BUILD / "setup" / "FAWAZ-Tenders-Setup.exe"
    shutil.copy2(setup, UPD / "FAWAZ-Tenders-Setup.exe")
    shutil.copy2(setup, ROOT / f"FAWAZ Tenders Setup {VERSION}.exe")
    base = update_url().rsplit("/", 1)[0]
    (UPD / "latest.json").write_text(json.dumps({
        "version": VERSION, "setup_url": f"{base}/FAWAZ-Tenders-Setup.exe" if base else "",
        "notes": CONF.get("notes", "")}, ensure_ascii=False, indent=1), encoding="utf-8")
    mb = setup.stat().st_size / 1e6
    print(f"\nDONE  version {VERSION}  setup {mb:.1f} MB  update url: {update_url() or '(GitHub not set yet)'}")


if __name__ == "__main__":
    main()
